### ISSUE TITLE
RTDB: Queued update calls have incorrect argument order

### ISSUE THREAD

**Issue by JapanYoshi** [Overvault-64/Firebase-Godot-API#4]
https://github.com/Overvault-64/Firebase-Godot-API/blob/cfa11ccf5b22b77cfbb3a4dc402cd6dfd92138de/addons/FirebaseAPI/realtime/reference.gd#L97

`update()` takes arguments in the order `data, path`.

https://github.com/Overvault-64/Firebase-Godot-API/blob/cfa11ccf5b22b77cfbb3a4dc402cd6dfd92138de/addons/FirebaseAPI/realtime/reference.gd#L132

Queued update events pass arguments in the order `path, data`.

**Comment by Overvault-64** [comment]
Damn! [Fixed](https://github.com/Overvault-64/Firebase-Godot-API/commit/635fdeb029c26cf168536610c7550a4b6b9deee9)
